# Generated by Django 3.1.1 on 2020-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('ip', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
