# Generated by Django 3.1.1 on 2020-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('ip', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Logging',
        ),
    ]
