# Generated by Django 3.1.1 on 2020-09-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200926_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoggingSystem',
            new_name='UserLogIp',
        ),
    ]
