# Generated by Django 3.1.1 on 2020-09-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200926_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogIp',
            new_name='UserIpLog',
        ),
    ]
